sudo: required

# This is a sample build configuration for TravisCI
language: java

services:
  - docker

# -B batch mode makes Maven less verbose
before_install:
  - docker pull djfarrelly/maildev

install:
  - docker run -d -p 1080:80 -p 1025:25 djfarrelly/maildev --name maildev
  - docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' maildev

script:
  - mvn -B clean verify
