sudo: required

# This is a sample build configuration for TravisCI
language: java

services:
  - docker

# -B batch mode makes Maven less verbose
install:
  - docker pull djfarrelly/maildev
  - docker run -p 1080:80 -p 1025:25 djfarrelly/maildev

script:
  - mvn -B clean verify
