sudo: required

# This is a sample build configuration for TravisCI
language: java

services:
  - docker
  - maildev

# -B batch mode makes Maven less verbose
script:
  - mvn -B clean verify
  - maildev --incoming-user user
  - maildev --incoming-pass 123