sudo: required

# This is a sample build configuration for TravisCI
language: java

services:
  - docker
  - maildev

# -B batch mode makes Maven less verbose
script:
  - maildev --outgoing-host localhost
  - maildev --outgoing-user user
  - maildev --outgoing-pass 123
  - mvn -B clean verify