sudo: required

# This is a sample build configuration for TravisCI
language: java

services:
  - docker

# -B batch mode makes Maven less verbose
script:
  - docker pull djfarrelly/maildev
  - docker run -p 1080:80 -p 1025:25 djfarrelly/maildev
  - docker-machine ip maildev
  - mvn -B clean verify
